### ISSUE TITLE
Queues do not always appear

### ISSUE THREAD

**Issue by Ubicall** [waleedsamy/CallCenterAgentApp#32]
i suspect it is related to not being to logout other user

**Comment by amegalla** [comment]
Handle the below error on first login:

```
will not log in comm server ~~beacuse~~ your are not logged in yet.
```

**Comment by waleedsamy** [comment]
this happen because flash loaded in login page and user does not has any credentials , which return error when try to authenticate with FS .
**solution :**
1. not load flash component when users in login , forget password or log out pages
   - which will give us a good benefit by decreasing number of open sessions on FS servers.
